accounts/urls.py
from django.urls import path
from .views import (
    IndexView,
    UserLoginView, UserHomeView, UserLogoutView,
    ContactFormView, PrivacyPolicyView
)

app_name = "accounts"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login", UserLoginView.as_view(), name="login"),
    path("home", UserHomeView.as_view(), name="home"),
    path("logout", UserLogoutView.as_view(), name="logout"),
    path("contact", ContactFormView.as_view(), name="contact"),
    path("privacy-policy", PrivacyPolicyView.as_view(), name="privacy_policy")
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

#from config.settings.dev import env
from config.settings.prod import env

urlpatterns = [
    path("", include("accounts.urls")),
    path(env("ADMIN_URL", default="admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATICFILES_DIRS
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += [path(env("SILK_URL", default="silk/"), include("silk.urls", namespace="silk"))]

accounts/models.py
import uuid

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):

    def create_user(self, username, email, password=None):

        if not username:
            raise ValueError("Users must have a username.")

        user = self.model(
            username=username,
            email=self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None):
        user = self.create_user(
            username=username,
            email=self.normalize_email(email),
            password=password
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(
        default=uuid.uuid4,
        primary_key=True,
        editable=False
    )
    username = models.CharField(
        verbose_name=_("username"),
        max_length=20,
        unique=True
    )
    email = models.EmailField(
        verbose_name=_("email address"),
        max_length=254,
        blank=True
    )
    is_active = models.BooleanField(
        verbose_name=_("active"),
        default=True
    )
    is_staff = models.BooleanField(
        verbose_name=_("staff"),
        default=False
    )

    objects = CustomUserManager()

    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.conf import settings
from django.core.mail import BadHeaderError, EmailMessage
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse


class UserLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs["placeholder"] = field.label
            field.label = ""


class ContactForm(forms.Form):

    name = forms.CharField(
        label="",
        max_length=20,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "お名前"
        })
    )
    email = forms.EmailField(
        label="",
        max_length=254,
        widget=forms.EmailInput(attrs={
            "class": "form-control",
            "placeholder": "メールアドレス"
        })
    )
    title = forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "件名"
        })
    )
    body = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={
            "class": "form-control",
            "placeholder": "本文"
        })
    )
    # captha = ReCaptchaField(widget=ReCaptchaWidget())

    def send_email(self):
        subject = "お問い合わせ：" + self.cleaned_data["title"]
        name = self.cleaned_data["name"]
        email = self.cleaned_data["email"]
        from_email = f"{name} <{email}>"
        message = self.cleaned_data["body"]
        recipient_list = [settings.EMAIL_HOST_USER]
        email_message = EmailMessage(
            subject, message, from_email, recipient_list, reply_to=[email]
        )
        try:
            email_message.send()
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView, FormView

from .forms import UserLoginForm, ContactForm


class IndexView(TemplateView):

    template_name = "accounts/index.html"


class UserLoginView(LoginView):

    form_class = UserLoginForm
    template_name = "accounts/login.html"


class UserHomeView(LoginRequiredMixin, TemplateView):

    template_name = "accounts/home.html"


class UserLogoutView(LogoutView):

    pass


class ContactFormView(FormView):

    form_class = ContactForm
    template_name = "accounts/contact.html"
    success_url = "accounts:contact"

    def form_valid(self, form):
        form.send_email()
        super().form_valid(form)


class PrivacyPolicyView(TemplateView):

    template_name = "accounts/privacy_policy.html"

templates/accounts/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}お問い合わせ{% endblock title %}

{% block main %}

<h2 class="text-center my-5">お問い合わせ</h2>


<div class="row my-5">

    <div class="col-md-8 mx-auto">

        <form action="" method="POST">
            {% csrf_token %}
        
            {% if form.non_field_errors %}
                <div class="text-danger font-weight-bold">
                    {% for err in form.non_field_errors %}
                        {{ err }}<br>
                    {% endfor %}
                </div>
            {% endif %}
        
            <div class="form-group">
                {% for field in form %}
        
                    {{ field.label_tag }}
                    {{ field }}
        
                    {% if field.errors %}
                        <div class="text-danger font-weight-bold">
                            {% for err in field.errors %}
                                {{ err }}<br>
                            {% endfor %}
                        </div>
                    {% endif %}
        
                {% endfor %}
            </div>
        
            <div class="text-center">
                <button type="submit" class="btn btn-outline-dark my-3">送信</button>
            </div>
        
        </form>

    </div>

</div>

{% endblock main %}

templates/accounts/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ホーム{% endblock title %}

{% block main %}

<h2 class="text-center my-5">{{ request.user }}さんのマイページ</h2>
<div class="text-center">
    <form method="POST" action="{% url 'accounts:logout' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-dark my-3">logout</button>
    </form>
</div>

{% endblock main %}

templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}トップ{% endblock title %}

{% block main %}

<h2 class="text-center my-5">サイトトップ</h2>

{% endblock main %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ログイン{% endblock title %}

{% block main %}

<h2 class="text-center my-5">ログイン</h2>

<div class="row my-5">

    <div class="col-md-4 mx-auto">

        <form action="" method="POST">
            {% csrf_token %}
        
            {% if form.non_field_errors %}
                <div class="text-danger font-weight-bold">
                    {% for err in form.non_field_errors %}
                        {{ err }}<br>
                    {% endfor %}
                </div>
            {% endif %}
        
            <div class="form-group">
                {% for field in form %}
        
                    {{ field.label_tag }}
                    {{ field }}
        
                    {% if field.errors %}
                        <div class="text-danger font-weight-bold">
                            {% for err in field.errors %}
                                {{ err }}<br>
                            {% endfor %}
                        </div>
                    {% endif %}
        
                {% endfor %}
            </div>
        
            <div class="text-center">
                <button type="submit" class="btn btn-outline-dark my-3">ログイン</button>
            </div>
        
        </form>

    </div>

</div>

{% endblock main %}

templates/accounts/privacy_policy.html
{% extends 'base.html' %}
{% load static %}

{% block title %}プライバシーポリシー{% endblock title %}

{% block main %}

<h2 class="text-center my-5">プライバシーポリシー</h2>

<h3 class="my-5">タイトル</h3>

<h4 class="my-5">サブタイトル</h4>

<p>本文</p>

{% endblock main %}

templates/base.html
<!DOCTYPE html>

<html lang="ja">



    <head>

        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        {% block css %}{% endblock css %}

        <title>{% block title %}{% endblock title %}</title>

    </head>



    <body>


        {% include 'snippets/header.html' %}


        <main class="container">

            {% block main %}{% endblock main %}
        
        </main>


        {% include 'snippets/footer.html' %}


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/472bba83f0.js" crossorigin="anonymous"></script>
        {% block js %}{% endblock js %}

        
    </body>



</html>

templates/snippets/footer.html
<footer>
    <div class="text-center">
        <small class="text-dark">©2024 Example Inc. All rights reserved. </small>
    </div>
</footer>

templates/snippets/header.html
<header>
    <nav class="navbar navbar-light bg-light">
        <div class="container">
            <h1><a class="navbar-brand" href="{% url 'accounts:index' %}">Navbar</a></h1>
        </div>     
    </nav>
</header>

templates/snippets/pagination.html
<nav aria-label="Page navigation">

    <ul class="pagination justify-content-center">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        {% for num in paginator.page_range %}
        {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}
            {% if page_obj.number == num %}
            <li class="page-item active">
                <span class="page-link">
                {{ num }}
                <span class="sr-only">(current)</span>
                </span>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}

    </ul>

</nav>